### PR TITLE
Completed css-brochure form challenge - Brandon Au

### PR DESCRIPTION
**Pull request by brandon-au**
css-brochure-form-screenshot

### CODE REVIEW

**Review by Zhiwutian — CHANGES_REQUESTED** [review]
Hey Brandon, its looking solid overall, a couple things to adjust:
1. You will want to adjust the outline of the inputs to more closely match the example
2.  The inputs should be a little bit taller to more closely match the example
3.  There should be a little more space between the inputs as in the example
4.  The form should be a little thinner which would more closely match the example.

Great work so far!

**Comment by brandon-au** [comment]
css-brochure-form-screenshot-rev1

**Comment by brandon-au** [comment]
css-brochure-form-screenshot-rev1

**Comment by brandon-au** [comment]
css-brochure-form-screenshot-rev2

**Review by Zhiwutian — APPROVED** [review]
👍🏼 Great work Brandon!

**Pull request merged**
